name: Build on push with tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Build
        run: |
          rake build

      - name: Check version
        id: version
        uses: actions/github-script@v7
        with:
          script: |
            if ("${{ github.ref }}".split("/").pop().match(/^v\d+\.\d+\.\d+.\d+$/)) {
              core.setOutput("prerelease", false);
            } else {
              core.setOutput("prerelease", true);
            }

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.version.outputs.prerelease }}
          body: |
            Download "-setup.exe".
          files: |
            ./build/*.*
